version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    build: ./server
    depends_on:
      - "postgres"

